#!/bin/bash
                                   #########
#################################### iSSH2 #####################################
#                                  #########                                   #
# Copyright (c) 2013 Tommaso Madonia. All rights reserved.                     #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of this software and associated documentation files (the "Software"), to deal#
# in the Software without restriction, including without limitation the rights #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell    #
# copies of the Software, and to permit persons to whom the Software is        #
# furnished to do so, subject to the following conditions:                     #
#                                                                              #
# The above copyright notice and this permission notice shall be included in   #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE  #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER       #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,#
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN    #
# THE SOFTWARE.                                                                #
################################################################################

downloadFile () {
  local url="$1"
  local path="$2"
  local filename="$(basename "$path")"

  if [[ ! -s "$path" ]];
  then
    echo "Downloading $filename"
    if ! curl --fail --location --retry 3 --retry-delay 1 \
      --connect-timeout 20 --progress-bar --output "$path" "$url"; then
      rm -f "$path"
      return 1
    fi
  else
    echo "$filename already exists"
  fi

  local md5="$(md5 -q "$path")"
  echo "MD5: $md5"
}

lipoFatLibrary () {
  local output="$1"
  shift
  local dirname="$(dirname "$output")"
  local filename="$(basename "$output")"

  echo "Building $filename fat library..."

  if [ ! -e "$dirname" ];
  then
    mkdir -p "$dirname"
  fi

  if [ -e "$output" ];
  then
    rm -f "$output"
  fi

  if [[ "$#" -eq 0 ]]; then
    echo "No input libraries were provided for $filename." >&2
    return 1
  elif [[ "$#" -eq 1 ]]; then
    cp "$1" "$output"
  else
    lipo -create "$@" -output "$output"
  fi
}

importHeaders () {
  local input=$1
  local output=$2

  echo "Copying headers..."
  rm -rf "$output"
  mkdir -p "$output"
  cp -RL "$input/." "$output/"
}

platformName () {
  case "$1" in
    macosx) echo "MacOSX" ;;
    iphonesimulator|appletvsimulator|watchsimulator)
      case "$1" in
        iphonesimulator) echo "iPhoneSimulator" ;;
        appletvsimulator) echo "AppleTVSimulator" ;;
        watchsimulator) echo "WatchSimulator" ;;
      esac ;;
    iphoneos)
      if [[ "$2" == "i386" ]] || [[ "$2" == "x86_64" ]]; then
        echo "iPhoneSimulator"
      else
        echo "iPhoneOS"
      fi ;;
    appletvos)
      if [[ "$2" == "i386" ]] || [[ "$2" == "x86_64" ]]; then
        echo "AppleTVSimulator"
      else
        echo "AppleTVOS"
      fi ;;
    watchos)
      if [[ "$2" == "i386" ]] || [[ "$2" == "x86_64" ]]; then
        echo "WatchSimulator"
      else
        echo "WatchOS"
      fi ;;
    *) echo "Unknown platform $1"
       exit 1 ;;
  esac
}

deploymentTargetFlag () {
  case "$1" in
    iphoneos) echo "-miphoneos-version-min" ;;
    iphonesimulator) echo "-miphonesimulator-version-min" ;;
    macosx) echo "-mmacosx-version-min" ;;
    appletvos) echo "-mtvos-version-min" ;;
    appletvsimulator) echo "-mtvos-simulator-version-min" ;;
    watchos) echo "-mwatchos-version-min" ;;
    watchsimulator) echo "-mwatchos-simulator-version-min" ;;
    *) echo "Unknown platform $1" >&2; return 1 ;;
  esac
}
